export const ADMIN_ROUTE = "/admin"
export const LOGIN_ROUTE = "/login"
export const REGISTRATION_ROUTE = "/reg"
export const SHOP_ROUTE = "/"
export const ORDER_ROUTE = "/order"
export const FLOWER_ROUTE = "/flower"